PROVIDER_NOT_FOUND = "Provider not found."
MODEL_NOT_FOUND = "LLM model not found."
API_KEY_REQUIRED = "API key is required for cloud models."
USER_CONFIG_NOT_FOUND = "No AI configuration found for this user."


class Provider:
    """Provider name constants used for matching against LLM provider names."""

    OPENAI = "OpenAI"
    ANTHROPIC = "Anthropic"
    GOOGLE = "Google"
    MISTRAL_AI = "Mistral AI"
    COHERE = "Cohere"
    AI21_LABS = "AI21 Labs"
    AMAZON_BEDROCK = "Amazon Bedrock"
    AZURE_OPENAI = "Azure OpenAI"
    GROQ = "Groq"
    REPLICATE = "Replicate"
    ALEPH_ALPHA = "Aleph Alpha"
    WRITER = "Writer"
    CEREBRAS = "Cerebras"
    HUGGING_FACE = "Hugging Face"
    OLLAMA = "Ollama"
    TOGETHER_AI = "Together AI"
    PERPLEXITY_AI = "Perplexity AI"
    XAI = "xAI"
    DEEPSEEK = "DeepSeek"
    FIREWORKS_AI = "Fireworks AI"
    SAMBANOVA = "SambaNova"
    LM_STUDIO = "LM Studio"
    LOCALAI = "LocalAI"
    JAN = "Jan"
    VLLM = "vLLM"
    LLAMA_CPP = "llama.cpp"
    KOBOLDCPP = "KoboldCpp"
    LLAMAFILE = "llamafile"
    TEXT_GENERATION_WEBUI = "Text Generation WebUI"
    GPT4ALL = "GPT4All"
